### ISSUE TITLE
Information missing in PDF export document

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#1]
Browser used: Safari

When a DMP template contains a question with a multiple choice answer format (e.g. check box, dropdown...), there is a text box below the answer options where users can write comments to clarify their selected response (e.g. https://preview.dmponline.be/projects/my-project-gdpr-record--3/plans/2332/edit).

![screen shot 2018-07-03 at 09 24 40](https://user-images.githubusercontent.com/13927732/42205623-4b5f92c8-7ea5-11e8-9f93-2dbbbe2f8131.png)

However, when the DMP is then exported as a PDF, the text in this 'Comment' box is not included in the export document (https://preview.dmponline.be/projects/my-project-gdpr-record--3/plans/2332/export?format=pdf). 

![screen shot 2018-07-03 at 09 35 52](https://user-images.githubusercontent.com/13927732/42205626-4eb4c1aa-7ea5-11e8-9ed1-71d31913b4f6.png)

On the other hand, when the DMP is exported as a plain text or docx file, the text from the 'Comment' box is included in the export document.

![screen shot 2018-07-03 at 09 37 53](https://user-images.githubusercontent.com/13927732/42205631-512bb722-7ea5-11e8-8edd-a1b79261b320.png)

**Comment by nicolasfranck** [comment]
ik kan de vragen van dat plan precies niet meer invullen?

**Comment by mm449** [comment]
Ik heb je inmiddels toegevoegd als co-owner van het plan.
