### ISSUE TITLE
export DMP in JATS XML

### ISSUE THREAD

**Issue by moreedri** [DMPbelgium/DMPonline_v4#11]
https://www.niso.org/standards-committees/jats

**Comment by moreedri** [comment]
follow the new reuse guidelines: https://jats4r.org/about-jats4r-recommendations

without breaking the default stylesheets: https://github.com/ncbi/JATSPreviewStylesheets

**Comment by laurastandaert** [comment]
Export of DMP in ma format is in development. Align to RDA maDMP standard format.
Ref: https://github.com/DMPbelgium/roadmap/issues/25
