### ISSUE TITLE
Default page upon login

### ISSUE THREAD

**Issue by frederikcoppens** [DMPbelgium/DMPonline_v4#12]
When login in, you always first get the "edit your profile" page, will in practice I (at least) almost always want to view (or create) a plan.

**Comment by moreedri** [comment]
Which login route do you use? ORCID? Institutional?

**Comment by moreedri** [comment]
Reproduced in both login scenario's

**Comment by moreedri** [comment]
Can we redirect after login to https://dmponline.be/projects ?
That is also in fact the home link (e.g. when clicking the logo top left)

**Comment by moreedri** [comment]
OK op test.dmponline.be ; settings redirect only for new users
