### ISSUE TITLE
Duplicating existing published template without publishing duplicate

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#14]
When an existing published template is duplicated within the same database, the duplicate itself is also set to "published", which means that it is immediately visible to end users. Is there a way to avoid this (other than by manually unchecking the "published" box in de duplicate template)?

**Comment by nicolasfranck** [comment]
should be retested on test.dmponline.be. Example to test against?

**Comment by mm449** [comment]
<https://test.dmponline.be/admin/dmptemplates/22>

**Comment by nicolasfranck** [comment]
Duplicate: https://test.dmponline.be/admin/dmptemplates/301
