### ISSUE TITLE
Display order of template phases

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#15]
When creating a template with various phases, each phase is assigned a number to determine the display order of the phases. However, the numbers assigned in the superadmin interface sometimes produce the wrong display order in the end user interface. 

E.g. in the example below: 
Phase 1 = Application DMP
Phase 2 = Full DMP

<img width="1403" alt="Screenshot 2019-03-27 at 12 12 51" src="https://user-images.githubusercontent.com/13927732/55071843-f6086e00-5089-11e9-9123-3d2bc1eff270.png">

<https://preview.dmponline.be/admin/dmptemplates/261>

in the end user interface results in: 
Phase 1 = Full DMP
Phase 2 = Application DMP

<img width="1050" alt="Screenshot 2019-03-27 at 12 16 14" src="https://user-images.githubusercontent.com/13927732/55072016-539cba80-508a-11e9-8b22-7abb0cd83bd4.png">

<https://preview.dmponline.be/projects/test-fwo-project>

**Comment by nicolasfranck** [comment]
fixed on test.dmponline.be

can only be tested when a new project is created

**Comment by mm449** [comment]
Seems to work in test
