### ISSUE TITLE
Hyperlinks not visible in section description

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#16]
Hyperlinks included in a description of a template section are not visible in the end user interface (orange hyperlink text against an orange background). 

<img width="1000" alt="Screenshot 2019-03-27 at 12 28 43" src="https://user-images.githubusercontent.com/13927732/55072639-e8ec7e80-508b-11e9-9e9e-9cf27122a77a.png">

<img width="1052" alt="Screenshot 2019-03-27 at 12 25 58" src="https://user-images.githubusercontent.com/13927732/55072477-81363380-508b-11e9-9976-a1787bbc6278.png">

**Comment by nicolasfranck** [comment]
@mm449 do you have an example to work on?

**Comment by mm449** [comment]
<https://preview.dmponline.be/projects/test-fwo-project/plans/3301/edit>
(open 'GDPR section: collection and processing of data')

**Comment by nicolasfranck** [comment]
should be fixed on production
