### ISSUE TITLE
Layout of list-style answer formats

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#17]
In the end user interface, the layout of list-style answer formats (e.g. check boxes) with longer-text answer options doesn't look great in terms of indentation. 

<img width="1044" alt="Screenshot 2019-03-27 at 12 42 01" src="https://user-images.githubusercontent.com/13927732/55073555-4e416f00-508e-11e9-81ee-dfd7801a0e17.png">

**Comment by laurastandaert** [comment]
lay out changed because of production update to Roadmap version (sept 2021)
