### ISSUE TITLE
Shared status in "view plans" list when owner has multiple roles

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#18]
When a plan owner has more than one role with regard to a plan (e.g. he/she is also Principal Investigator), the "My plans" list will indicate that this plan has been shared "with 1 people". This is confusing because in this case, the plan is not actually shared with another user (it just means that the same user has multiple roles in connection to the plan). 

<img width="1112" alt="Screenshot 2019-03-27 at 13 03 12" src="https://user-images.githubusercontent.com/13927732/55075207-b3975f00-5092-11e9-89ef-f0319733339b.png">

<img width="1059" alt="Screenshot 2019-03-27 at 13 21 34" src="https://user-images.githubusercontent.com/13927732/55075449-4e903900-5093-11e9-8314-48bd3cb805cd.png">

**Comment by nicolasfranck** [comment]
fixed on test.dmponline.be

**Comment by mm449** [comment]
Ok
