### ISSUE TITLE
Increase maximum number of pages in template settings

### ISSUE THREAD

**Issue by mm449** [DMPbelgium/DMPonline_v4#19]
The maximum number of pages for a plan can be determined in the template settings in the superadmin interface. 

<img width="1399" alt="Screenshot 2019-03-27 at 14 35 00" src="https://user-images.githubusercontent.com/13927732/55080093-cb281500-509d-11e9-8115-8fbe474108f9.png">

It is currently not possible to set this number to more than 10 pages. However, some templates (e.g. funder templates with additional GDPR sections from an institution) are rather long. In those cases, simply displaying all the sections and questions in the export document already takes up much of the available space. Can we increase the maximum page limit so that end users will have enough space for their answers for each template?

**Comment by nicolasfranck** [comment]
@mm449 : instead of a selectbox, better a number input, with minimum "1" and maximum "100", and default "3" (that is not configured as such)?

cf. https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_number

**Comment by nicolasfranck** [comment]
see test.dmponline.be

**Comment by mm449** [comment]
Seems to work
