### ISSUE TITLE
Notification option

### ISSUE THREAD

**Issue by frederikcoppens** [DMPbelgium/DMPonline_v4#2]
I support our researchers in filling in the DMP. If I've added text or comments there is (as far as I know) no way to notify the person who gave me access that I did.  A (optional) "send mail to owner" option would be useful

**Comment by moreedri** [comment]
to be discussed with related feature requests:

- be notified of a comment on a plan you own/edit/...
- be notified of changes by other users
- actively send a message to a number of users (e.g. by role, "contact the owners")
- have a concise view of all the (recent) comments across the template
- have a concise view of all the (recent) edits across the template
- actively forward a comment or an edit to a number of users
- manage personal notification preferences

**Comment by laurastandaert** [comment]
See functionality to manage settings in roadmap software via > edit profile > Notification preferences tab
implemented since upgrade to roadmap software (sept 2021)
