### ISSUE TITLE
daily JSON export of all GDPR-true plans for an organisation

### ISSUE THREAD

**Issue by moreedri** [DMPbelgium/DMPonline_v4#20]

**Comment by nicolasfranck** [comment]
This needs more clarification.

* What do you need exactly in this xlsx?
* Who is this for? Backup?

**Comment by nicolasfranck** [comment]
there is an export for a single plan available (i.e a Version, so only one Phase!) in CSV format, that gives the following output fields:

- "Section"
- "Question"
- "Answer"
- "Selected option(s)"
- "Answered by"
- "Answered at"

**Comment by nicolasfranck** [comment]
TODO: add url to the given "section"/"question"

**Comment by moreedri** [comment]
update: not needed in xlsx, json is OK

**Comment by laurastandaert** [comment]
documentation is located here: https://github.com/DMPbelgium/DMPonline_v4/blob/master/dmp_jsonapi.md
