### ISSUE TITLE
DPO user cannot comment (viewing rights needed)

### ISSUE THREAD

**Issue by moreedri** [DMPbelgium/DMPonline_v4#21]
DPO user cannot comment because not enough viewing rights for all tabs?

![afbeelding](https://user-images.githubusercontent.com/36739/57141356-4b871780-6dba-11e9-8256-a689ff727704.png)

**Comment by nicolasfranck** [comment]
A user can comment if he/she has edit rights to the project. A DPO has only readonly access.

**Comment by nicolasfranck** [comment]
Something to think about: the tab of the plan is setup as a form to be filled in. That's why it is visible only to those with edit rights, and that's why commenting is only possible by those who have those same rights.

**Comment by laurastandaert** [comment]
permission system updated because of upgrade to roadmap software (sept 2021)
