### ISSUE TITLE
Adapt guidance AFTER creating a new plan

### ISSUE THREAD

**Issue by NelePauwels** [DMPbelgium/DMPonline_v4#22]
After creating a new plan, it is not possible to add additional guidance e.g. from DCC or from a faculty. Is it possible to add that feature? It is of interest for the users when the guidance of the Faculty of Life Sciences and Medicine will be added to the tool.

**Comment by nicolasfranck** [comment]
why not simply create a new template? If needed we can duplicate existing templates (only from the command line, not by some button in the website).

**Comment by NelePauwels** [comment]
We are currently working on guidance for users of the Faculty of Life Sciences and Medicine. When users are creating their DMP at the moment that the guidance will be included, they can benefit from the option to choose the newly added guidance in their existing DMP.
It is the goal that the guidance can be requested, starting from all templates (e.g. GDPR record).

**Comment by laurastandaert** [comment]
Possible since update to Roadmap software (sept 2021)
