### ISSUE TITLE
Date of last update: automatically generated instead of manual? 

### ISSUE THREAD

**Issue by NelePauwels** [DMPbelgium/DMPonline_v4#23]
The date of last update should now be adapted manually each time a user makes some adaptations. Is it possible to generate this data automatically?

**Comment by nicolasfranck** [comment]
Can you show me an example, by url?

**Comment by NelePauwels** [comment]
Example: https://dmponline.be/projects/dmp-workshop-04-04-2019/plans/20111/edit
The date of last update is now left blank, unless I manually give in the date and adapt it manually every time I make some changes etc.

**Comment by nicolasfranck** [comment]
Ah, now I see: it is just a question from the template that needs to be filled in.

As with all questions, there is no way to automatically fill it.
But I guess, the name itself leads to certain expectations.

For each "thing" (templates, projects .. ) in dmponline we keep dates like "date created" and "date updated" at database level, and that's filled in automatically. But it is not shown everywhere.

@mm449 is this actually meant to be a question?

**Comment by mm449** [comment]
@nicolasfranck: I think it should be clear to end users when a plan was created, and when it was last updated (ideally on both the edit page and the export document). If this can be done in another way than via a template question, that seems fine (and even better) to me.

**Comment by nicolasfranck** [comment]
@mm449 agreed, but I think in this case, it's a misunderstanding: the question in the template has the title "last updated". See above.

**Comment by laurastandaert** [comment]
automated timestamp vs template question
