### ISSUE TITLE
No clear message when not filling in the requested DMP title

### ISSUE THREAD

**Issue by NelePauwels** [DMPbelgium/DMPonline_v4#24]
When the user forgets to fill in a title, there is no clear error message. Moreover, it seems that you can click on 'yes, create plan', but nothing happens. A required title is an added value, but it is at this stage unclear that you have forgotten to add one (although the red text)...

Can a clear error message be added? 

![image](https://user-images.githubusercontent.com/50873128/58097397-8de08f00-7bd7-11e9-9228-7d26cdec7753.png)

**Comment by nicolasfranck** [comment]
Something like:

Title: <Please fill in!>

and disable the confirm button?

**Comment by NelePauwels** [comment]
Yes, both actions (message and disabling the confirm button) seem informative for the user. Please include the actions preferably at this page: https://dmponline.be/projects/new. (i.a. before the screen 'confirm plan details').

**Comment by laurastandaert** [comment]
since upgrade to roadmap, create plan form has been updated: no confirmation popup anymore.
Blank title is automatically filled with "`User`'s plan"
