### ISSUE TITLE
Permission vs. role? 

### ISSUE THREAD

**Issue by NelePauwels** [DMPbelgium/DMPonline_v4#25]
When sharing your DMP, you have options to choose between some 'permissions' such as edit and read only. This seems clear. However, other 'permissions' such as DPO, Data Contact, etc more reflect roles related to the project. 
Is it possible to increase the possibilities (DPO with orwithout edit rights) and to increase clarity by making a distinction between 'permission' and 'role'?

**Comment by laurastandaert** [comment]
Contributor and collaborator roles have been updated since update to roadmap software (sept 2021). Issue no longer applicable
