### ISSUE TITLE
login using ORCID

### ISSUE THREAD

**Issue by frederikcoppens** [DMPbelgium/DMPonline_v4#26]
When logging in with ORCID (because a collaborator does not have the university account yet), the authorization on the ORCID side looks good, but DMPonline gives an error that it cannot get the email address

**Comment by nicolasfranck** [comment]
You need to set the visibility of your email to either:

* public (visible to the whole world, i.e. on your public orcid page)
* trusted parties (only visible to trusted parties like dmponline.be)

If it's private, then no external application can read it. That's probably the case here.

To do this, go to your orcid profile page, and edit your email addresses.
A form will popup, showing you the visibility to right.

**Comment by frederikcoppens** [comment]
The account in question (not mine) has several email addresses associated, the one used for DMPonline is set to trusted parties. Could the presence of other email addresses set to private cause an issue ?

**Comment by nicolasfranck** [comment]
We use the primary email address. If you set the visibility of this primary email address to private, then dmponline cannot read it.

**Comment by floradanna** [comment]
I changed the visibility of my primary email address and now I can login, thanks. However, I don't see the 'Create plans' button from the 'My plans' page.

**Comment by nicolasfranck** [comment]
ah, that's because we could not link you to an organisation. In that case you are "guest", and only able to read. I assume you are linked to Ghent University in some way, looking at your email?

**Comment by floradanna** [comment]
yes, I am at VIB Plant System Biology, UGent. I just don't have an UGent account yet.

**Comment by nicolasfranck** [comment]
done, you're linked
