### ISSUE TITLE
Authorisation: readonlyaccess to filled in DMP/GDPR report by other groups

### ISSUE THREAD

**Issue by denshade** [DMPbelgium/DMPonline_v4#27]
Is there a way, or are there plans to allow readonly access to filled in DMP/GDPR plans for review by a group of people?(e.g. Ethics  committee)

**Comment by nicolasfranck** [comment]
For now there is only one way: export the plan to pdf or word.

The plan in the web interface is basically a web form, so no.

**Comment by denshade** [comment]
Thanks for your answer!
