### ISSUE TITLE
University account not linked to organisation

### ISSUE THREAD

**Issue by wouterschurgers** [DMPbelgium/DMPonline_v4#29]
I don't see the 'Create plans' button from the 'My plans' page. When I check my profile under 'Edit profile', it lists my organisation as being 'guests' instead of my university. However, when I signed in, it took me to the correct login page and i am able to sign in. How can my account be linked to my university?

**Comment by nicolasfranck** [comment]
Ah, you logged in with ORCID, so the organisation was not set automatically based on your email address. I updated your record accordingly. Please use your institutional login.

**Comment by wouterschurgers** [comment]
Thank you for the quick response!
