### ISSUE TITLE
Email template "access given"

### ISSUE THREAD

**Issue by frederikcoppens** [DMPbelgium/DMPonline_v4#3]
It would be nice to also have the name and email of the person that gave you access to a DMP in the email. Now it only gives the project name. 

Reason: people give me access on different email addresses, and I would like to 'redirect' them use my Ugent.be email (for which I have an account already)

**Comment by moreedri** [comment]
make a better template

**Comment by nicolasfranck** [comment]
https://github.com/DMPbelgium/DMPonline_v4/commit/6e6cc93471302866dbfc94652dff379ac5c19c3e

**Comment by moreedri** [comment]
Hello, 

You have been given access to the Data Management Plan for the project "<insert project name + hyperlink to the plan>". 

To access the plan, sign into [DMPonline.be](https://dmponline.be) with your institutional account or, if your institution is not listed on the login page, your ORCID iD. 

with regard,
DMPonline.be on behalf of 

<insert names of owner and co-owners and principal investigator with role>

**Comment by frederikcoppens** [comment]
after the "on behalf of" you would then have <owner name> ?

**Comment by moreedri** [comment]
can be tested on test.dmponline.be with simpler wording:

Hello **NAME**

**USER** (**EMAIL**) has given you access level "Read only" to the DMP "My project (Faculty of Law & Criminology DMP)".

Sign in with **ORCID** ( https://test.dmponline.be/users/auth/orcid )

**Comment by frederikcoppens** [comment]
is ORCID the only option because it is the test environment ? Can't test as I get "We're sorry. Something went wrong"

**Comment by nicolasfranck** [comment]
yes, I'm sorry, there is something on the test server. I'll notify when it's fixed.

**Comment by nicolasfranck** [comment]
@frederikcoppens : test.dmponline.be is back online

**Comment by laurastandaert** [comment]
Changes implemented and may be improved further because of update to roadmap code base (since sept 2021)
