### ISSUE TITLE
Bug: Partially filled DMP sections - questions considered as answered even if empty

### ISSUE THREAD

**Issue by aaikedw** [DMPbelgium/DMPonline_v4#34]
If a question section is opened for editing, and then closed (clicking "+), the user is presented with a save dialog even if nothing has been modified, choosing "Save" results in all questions being considered as answered regardless which of the individual  questions which have been answered or not. 

![CleanShot 2020-08-18 at 11 54 10](https://user-images.githubusercontent.com/9320501/90500027-9f05ac00-e14a-11ea-97dd-0db90885144e.png)

This dialog also pops up even if an a single question has been answered and saved, which seems confusing to me. If users don't click "discard" in this scenario, the questions answered count will be off again.

Not sure this may be related, but it seems those "empty responses" somehow get populated with whitelines after saving.

**Comment by laurastandaert** [comment]
Issue no longer applicable. Upgrade to roadmap software (sept 2021) has introduced autosave functionality
