### ISSUE TITLE
Feature request: re-use DMP answers in other template

### ISSUE THREAD

**Issue by aaikedw** [DMPbelgium/DMPonline_v4#36]
I presume this may require the implementation of the concept of machine actionable DMPs, but it would seem very useful to be able to re-use content of an existing DMP in another template. 

This would e.g. allow to pick up a DMP in a funder template and turn it into a DMP in the institutional template, a DMP for internal use or similar.

Happy to elaborate more in case this feature would be of interest to other partners.

**Comment by laurastandaert** [comment]
Since update to Roadmap software, copy of a plan and of a template have become possible, and hence partially fulfill this request. 
Referenced in https://github.com/DMPbelgium/roadmap/issues/21 and https://github.com/DMPbelgium/roadmap/issues/16
