### ISSUE TITLE
Force updating title

### ISSUE THREAD

**Issue by frederikcoppens** [DMPbelgium/DMPonline_v4#4]
Most DMPs that are shared with me have the title "My project (FWO DMP)". Is it possible to force people to change this ? Or give some feedback that this is not the most useful thing to leave it to the default ?

**Comment by moreedri** [comment]
**CURRENT BEHAVIOUR**
Upon creating a new plan, the controller prefills the "project name" with dummy text consisting of "My project" plus the name of the template in brackets ; this is necessary because RoR cannot have an empty page title.

**Comment by moreedri** [comment]
**TOBE**
Upon creating a new plan, render the page with a default page title "New project" plus the name of the template in brackets. Leave the field "project name" blank. Make the field "project name" required.

**Comment by nicolasfranck** [comment]
Or leave the input empty, making it required as is.

The template is to be selected yet, so one cannot add the template name to the project title as default

**Comment by moreedri** [comment]
OK op preview.dmponline.be
