### ISSUE TITLE
Radio buttons marked as "default" in orgadmin should be preselected when user creates a plan

### ISSUE THREAD

**Issue by moreedri** [DMPbelgium/DMPonline_v4#7]
Orgadmin template editor allows for the creation of structured responses of different types (dropdown, checkboxes, radios), allowing one of the options to be marked as default answer. 

**CURRENT SITUATION**
Marking as "default" has no effect

**TOBE**
Enforce default answer

**Comment by moreedri** [comment]
bijv https://test.dmponline.be/org/admin/templates/291/admin_phase?edit=true&question_id=2291&section_id=1031&version_id=451

dit is de org admin area, waar je aangeeft dat iets het default antwoord moet zijn

**Comment by moreedri** [comment]
bijv https://test.dmponline.be/projects/verplichte-titel/plans/2811/edit

dit is een nieuw plan gecreëerd met bovenstaand template, maar het default antwoord wordt hier niet toegepast

**Comment by nicolasfranck** [comment]
het is erger dan gedacht: het aangevinkte antwoord wordt ook niet getoond (yes of no)

cf. https://github.com/justinfrench/formtastic/wiki/Deprecation-of-%3Aselected-option

**Comment by moreedri** [comment]
OK op preview.dmponline.be
